name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
      - feature1
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.verbose=true
            -Dsonar.projectKey=FirstCLI_GitHub_Action
            -Dsonar.projectName=FirstCLI_GitHub_Action
            -Dsonar.projectVersion=1.0
            -Dsonar.sources="src/javascript,src/python"
            -Dsonar.sourceEncoding=UTF-8
